version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Etc/UTC
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
    open-pull-requests-limit: 5

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Etc/UTC
    labels:
      - dependencies
      - gradle
    commit-message:
      prefix: build
    open-pull-requests-limit: 5
